### ISSUE TITLE
deleting tuntap requires mode

### ISSUE THREAD

**Issue by nickbeee** [dmbaturin/iproute2-cheatsheet#19]
Thanks for a really helpful resource. 
On my system 
`Linux nickb-Precision-M20 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:30:51 UTC 2017 i686 i686 i686 GNU/Linux`

`ip tuntap del dev tap0` 
does not work it's actually 
`ip tuntap del dev tap0 mode tap`

**Comment by dmbaturin** [comment]
That's a good catch, thanks! I've fixed it and added some explanations: https://github.com/dmbaturin/iproute2-cheatsheet/commit/2d1a416489e4f8520560e9ae295d8489aeb25ebf
