### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by xnox** [dmbaturin/iproute2-cheatsheet#25]
lets encrypt ssl certificate appears to have expired on Thursday, June 7, 2018 at 11:04:09 AM

Please update?

**Comment by dmbaturin** [comment]
I should setup auto-update for those letsencrypt certs. In fact, I thought I do have it set up.
I've renewed the certs, please re-test.

**Comment by xnox** [comment]
Looks good =) At least until 6th of September 😜
