### ISSUE TITLE
The git doesn't contain the css in your site

### ISSUE THREAD

**Issue by elico** [dmbaturin/iproute2-cheatsheet#5]
The git doesn't contain the css in your site and it looks a bit different.
can you add it please?

**Comment by dmbaturin** [comment]
This is a bit puzzling. I deploy it simply by copying it from git to there, and the hint.css file it references doesn't exist on my web server either. I'm not even sure why that line is there.

**Comment by elico** [comment]
After you asked me about styling ideas I have been looking at something and was wondering what do you think about this:
http://ngtech.co.il/tmp/index_nocss.html

**Comment by dmbaturin** [comment]
Since we merged the improving style, I think this is no longer an issue and should be closed. ;)
